Repository heremaps/here-data-sdk-cpp, pull requests merged in 2019-08, with the labels that each got.

#58 Extend information about platforms, requirements and dependencies.
  README.md
Labels: documentation

#62 Add the architecture overview document
  docs/GettingStartedGuide.md
  docs/OverallArchitecture.md
  docs/diagrams/sdk-module-overview.png
  docs/diagrams/sdk-module-overview.puml
Labels: documentation

#78 Rename NetworkStatus to SendOutcome to mark it is a outcome class.
  olp-cpp-sdk-core/include/olp/core/network2/Network.h
  olp-cpp-sdk-core/include/olp/core/network2/NetworkTypes.h
Labels: enhancement

#76 TaskScheduler added to OlpClientSettings
  olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
  olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
  olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
Labels: enhancement

#77 Setup Travis CI to build Android and IOS EXAMPLES
  .travis.yml
  README.md
  examples/helpers/android/app/CMakeLists.txt.in
  examples/helpers/android/app/build.gradle.in
  examples/helpers/cmake/gen_android_example.cmake.in
  scripts/android/build.sh
  scripts/ios/build.sh
Labels: CI

#81 Renamed folder and namespace network2 to http.
  olp-cpp-sdk-core/CMakeLists.txt
  olp-cpp-sdk-core/include/olp/core/http/Network.h
  olp-cpp-sdk-core/include/olp/core/http/NetworkProxySettings.h
  olp-cpp-sdk-core/include/olp/core/http/NetworkRequest.h
  olp-cpp-sdk-core/include/olp/core/http/NetworkResponse.h
  olp-cpp-sdk-core/include/olp/core/http/NetworkSettings.h
  olp-cpp-sdk-core/include/olp/core/http/NetworkTypes.h
  olp-cpp-sdk-core/src/http/NetworkProxySettings.cpp
  olp-cpp-sdk-core/src/http/NetworkRequest.cpp
  olp-cpp-sdk-core/src/http/NetworkResponse.cpp
  olp-cpp-sdk-core/src/http/NetworkSettings.cpp
  olp-cpp-sdk-core/src/network2/Network.cpp
Labels: enhancement

#70 Added iOS implementation of Network2 interface
  olp-cpp-sdk-core/cmake/ios.cmake
  olp-cpp-sdk-core/include/olp/core/http/NetworkTypes.h
  olp-cpp-sdk-core/src/http/ios/OLPHttpClient+Internal.h
  olp-cpp-sdk-core/src/http/ios/OLPHttpClient.h
  olp-cpp-sdk-core/src/http/ios/OLPHttpClient.mm
  olp-cpp-sdk-core/src/http/ios/OLPHttpTask+Internal.h
  olp-cpp-sdk-core/src/http/ios/OLPHttpTask.h
  olp-cpp-sdk-core/src/http/ios/OLPHttpTask.mm
  olp-cpp-sdk-core/src/http/ios/OLPNetworkConstants.h
  olp-cpp-sdk-core/src/http/ios/OLPNetworkConstants.mm
  olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.h
  olp-cpp-sdk-core/src/http/ios/OLPNetworkIOS.mm
Labels: enhancement

#90 Linux FV build and tests. Setup Doxygen build.
  .gitlab-ci.yml
  .travis.yml
  scripts/linux/fv/gitlab-olp-cpp-sdk-authentication-test.sh
  scripts/linux/fv/gitlab-olp-cpp-sdk-core-cache-test.sh
  scripts/linux/fv/gitlab-olp-cpp-sdk-core-client-test.sh
  scripts/linux/fv/gitlab-olp-cpp-sdk-core-geo-test.sh
  scripts/linux/fv/gitlab-olp-cpp-sdk-core-network-test.sh
  scripts/linux/fv/gitlab-olp-dataservice-read-test.sh
  scripts/linux/fv/gitlab-olp-dataservice-write-test.sh
  scripts/linux/fv/gitlab_build_fv.sh
  scripts/linux/fv/gitlab_test_fv.sh
  scripts/linux/fv/olp-common.variables
  scripts/linux/fv/olp-cpp-sdk-core-authentication-test.variables
  scripts/linux/fv/olp-cpp-sdk-core-cache-test.variables
  scripts/linux/fv/olp-cpp-sdk-core-client-test.variables
  scripts/linux/fv/olp-cpp-sdk-core-geo-test.variables
  scripts/linux/fv/olp-cpp-sdk-core-network-test.variables
  scripts/linux/fv/olp-dataservice-read-test.variables
  scripts/linux/fv/olp-dataservice-write-test.variables
  scripts/linux/psv/travis_build_psv.sh
  scripts/linux/psv/travis_test_psv.sh
Labels: CI

#97 Add china URLs to read and write lookup API.
  olp-cpp-sdk-core/src/logging/MessageFormatter.cpp
  olp-cpp-sdk-dataservice-read/src/ApiClientLookup.cpp
  olp-cpp-sdk-dataservice-write/src/ApiClientLookup.cpp
Labels: enhancement
