Repository heremaps/here-data-sdk-cpp, pull requests merged in 2019-11, with the labels that each got.

#279 Reviewed IndexLayerClient and StreamLayerClient
  olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/IndexLayerClient.h
  olp-cpp-sdk-dataservice-write/include/olp/dataservice/write/StreamLayerClient.h
Labels: documentation

#363 Adapts AutoRefreshingToken class to coding style.
  olp-cpp-sdk-authentication/src/AutoRefreshingToken.cpp
Labels: enhancement

#366 Create NightVerify pipeline with Valgrind. Add CppCheck and SonarQube
  .gitlab-ci.yml
  scripts/linux/fv/gitlab-olp-cpp-sdk-dataservice-read-test.sh
  scripts/linux/fv/gitlab-olp-cpp-sdk-dataservice-write-test.sh
  scripts/linux/fv/gitlab_build_fv.sh
  scripts/linux/fv/gitlab_test_fv.sh
  scripts/linux/fv/olp-cpp-sdk-dataservice-read-test.variables
  scripts/linux/fv/olp-cpp-sdk-dataservice-write-test.variables
  scripts/linux/nv/gitlab_build_valgrind.sh
  scripts/linux/nv/gitlab_cppcheck_and_upload_sonar.sh
  scripts/linux/nv/gitlab_test_valgrind.sh
  scripts/linux/nv/sonar-project.propertiesValgrind
Labels: CI

#380 Adapts InMemoryCache class to coding style.
  olp-cpp-sdk-core/src/cache/InMemoryCache.cpp
  olp-cpp-sdk-core/src/cache/InMemoryCache.h
  olp-cpp-sdk-core/tests/cache/InMemoryCacheTest.cpp
Labels: enhancement

#393 Add copyright on top of all bash scripts
  scripts/android/build.sh
  scripts/ios/build.sh
  scripts/linux/fv/gitlab-olp-cpp-sdk-authentication-test.sh
  scripts/linux/fv/gitlab-olp-cpp-sdk-core-test.sh
  scripts/linux/fv/gitlab-olp-cpp-sdk-dataservice-read-test.sh
  scripts/linux/fv/gitlab-olp-cpp-sdk-dataservice-write-test.sh
  scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
  scripts/linux/fv/gitlab-olp-cpp-sdk-integration-test.sh
  scripts/linux/fv/gitlab_build_fv.sh
  scripts/linux/fv/gitlab_test_fv.sh
  scripts/linux/nv/gitlab_build_valgrind.sh
  scripts/linux/nv/gitlab_cppcheck_and_upload_sonar.sh
  scripts/linux/nv/gitlab_test_valgrind.sh
  scripts/linux/psv/travis_build_psv.sh
  scripts/linux/psv/travis_test_psv.sh
  scripts/macos/psv/travis_build_psv.sh
Labels: CI

#398 Fix wrong include path for iOS HTTP layer.
  olp-cpp-sdk-core/cmake/ios.cmake
Labels: bug

#399 Add OLP_SDK_NO_EXCEPTION to ON in Nighly build script
  scripts/linux/nv/gitlab_build_valgrind.sh
Labels: CI

#407 Move OSX/IOS builds from Travis to Azure
  .travis.yml
  azure-pipelines.yml
  scripts/ios/azure_ios_build_psv.sh
  scripts/macos/psv/azure_macos_build_psv.sh
Labels: CI

#428 Small changes needed for VersionedLayerClient::PrefetchTiles.
  olp-cpp-sdk-core/include/olp/core/client/ApiResponse.h
  olp-cpp-sdk-core/include/olp/core/client/CancellationContext.h
  olp-cpp-sdk-core/include/olp/core/client/CancellationContext.inl
  olp-cpp-sdk-core/include/olp/core/client/TaskContext.h
  olp-cpp-sdk-core/tests/client/TaskContextTest.cpp
Labels: enhancement

#430 Adds version to PrefetchTileRequest.
  olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTileResult.h
  olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
  olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/Types.h
Labels: enhancement

#450 Add retry to FV and NV online tests
  scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
  scripts/linux/nv/gitlab_test_valgrind.sh
Labels: CI

#446 Add nightly performance tests into Gitlab NV pipeline
  .gitlab-ci.yml
  scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
  scripts/linux/nv/gitlab_test_performance.sh
Labels: CI

#453 Fix FV pipeline failure due to file not found
  .gitlab-ci.yml
Labels: CI, bug

#432 Refactors VersionedLayerClient::PrefetchTiles now using TaskScheduler.
  olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
  olp-cpp-sdk-dataservice-read/src/PrefetchTilesProvider.cpp
  olp-cpp-sdk-dataservice-read/src/PrefetchTilesProvider.h
  olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.cpp
  olp-cpp-sdk-dataservice-read/src/VersionedLayerClientImpl.h
  olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.cpp
  olp-cpp-sdk-dataservice-read/src/repositories/PrefetchTilesRepository.h
  tests/integration/olp-cpp-sdk-dataservice-read/VersionedLayerClientTest.cpp
Labels: enhancement

#460 Add fix to retry mechanism for NV/FV online tests.
  scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
  scripts/linux/nv/gitlab_test_valgrind.sh
Labels: CI

#463 Modify retry mechanism for NV/FV online tests
  scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
  scripts/linux/fv/gitlab_test_fv.sh
  scripts/linux/nv/gitlab_test_valgrind.sh
Labels: CI

#471 Fix retry mechanism in FV/Nv online tests
  scripts/linux/fv/gitlab-olp-cpp-sdk-functional-test.sh
  scripts/linux/fv/gitlab_test_fv.sh
  scripts/linux/nv/gitlab_test_valgrind.sh
Labels: CI
