Repository heremaps/here-data-sdk-cpp, pull requests merged in 2019-07, with the labels that each got.

#3 Fix typo in NetworkSystemConfig.cpp
  olp-cpp-sdk-core/src/network/NetworkSystemConfig.cpp
Labels: bug

#4 Fixed CMake configuration errors of Android tests
  .gitignore
  cmake/android/tester/app/build.gradle.in
  cmake/android/tester/build.gradle
Labels: bug

#2 Fix file system operations on Windows
  olp-cpp-sdk-core/src/utils/Dir.cpp
Labels: bug

#8 Fixed linker errors when using EDGE SDK in other HERE Android projects
  olp-cpp-sdk-core/cmake/android.cmake
  olp-cpp-sdk-core/src/network/android/NetworkProtocol.java
  olp-cpp-sdk-core/src/network/android/NetworkProtocolAndroid.cpp
  olp-cpp-sdk-core/src/network/android/NetworkSSLContextFactory.java
  olp-cpp-sdk-core/src/network/ios/HttpClient.mm
Labels: bug

#7 Create initial Travis CI configuration
  .gitignore
  .travis.yml
  olp-cpp-sdk-core/tests/cache/unittest/DefaultCacheTest.cpp
  scripts/linux_build.sh
  scripts/windows_build.sh
Labels: enhancement

#6 Added Android gradle template for the dataservice-write example
  docs/dataservice-write-example.md
  examples/.gitignore
  examples/dataservice-write/CMakeLists.txt
  examples/dataservice-write/example.cpp
  examples/helpers/android/app/CMakeLists.txt.in
  examples/helpers/android/app/build.gradle.in
  examples/helpers/android/app/proguard-rules.pro
  examples/helpers/android/app/src/main/AndroidManifest.xml.in
  examples/helpers/android/app/src/main/cpp/MainActivityNative.cpp.in
  examples/helpers/android/app/src/main/java/MainActivity.java.in
  examples/helpers/android/app/src/main/res/layout/activity_main.xml
  examples/helpers/android/app/src/main/res/values/colors.xml
  examples/helpers/android/app/src/main/res/values/strings.xml.in
  examples/helpers/android/app/src/main/res/values/styles.xml
  examples/helpers/android/build.gradle
  examples/helpers/android/gradle.properties
  examples/helpers/android/gradle/wrapper/gradle-wrapper.jar
  examples/helpers/android/gradle/wrapper/gradle-wrapper.properties
  examples/helpers/android/gradlew
  examples/helpers/android/gradlew.bat
  examples/helpers/android/settings.gradle
  olp-cpp-sdk-core/CMakeLists.txt
Labels: enhancement

#11 Fix boost issue on windows
  CMakeLists.txt
  README.md
  external/boost/CMakeLists-Boost.txt
  external/boost/CMakeLists.txt
  external/boost/CMakeLists.txt.boost.in
  olp-cpp-sdk-authentication/test/unit/ArcGisTestUtils.cpp
  olp-cpp-sdk-authentication/test/unit/AuthenticationProductionTests.cpp
  olp-cpp-sdk-authentication/test/unit/AuthenticationTests.h
  olp-cpp-sdk-authentication/test/unit/FacebookTestUtils.cpp
  olp-cpp-sdk-authentication/test/unit/GoogleTestUtils.cpp
  olp-cpp-sdk-authentication/test/unit/TestHereAccountOauth2IntegrationOnline.cpp
  olp-cpp-sdk-authentication/test/unit/main.cpp
  olp-cpp-sdk-core/CMakeLists.txt
  olp-cpp-sdk-dataservice-read/CMakeLists.txt
  olp-cpp-sdk-dataservice-read/test/unit/CMakeLists.txt
  olp-cpp-sdk-dataservice-read/test/unit/src/ApiTest.cpp
  olp-cpp-sdk-dataservice-read/test/unit/src/CatalogClientTest.cpp
  olp-cpp-sdk-dataservice-read/test/unit/src/main.cpp
  olp-cpp-sdk-dataservice-write/test/CMakeLists.txt
  olp-cpp-sdk-dataservice-write/test/DataserviceWriteTestMain.cpp
  olp-cpp-sdk-dataservice-write/test/unit/TestIndexLayerClient.cpp
  olp-cpp-sdk-dataservice-write/test/unit/TestStreamLayerClient.cpp
  olp-cpp-sdk-dataservice-write/test/unit/TestVersionedLayerClient.cpp
  olp-cpp-sdk-dataservice-write/test/unit/TestVolatileLayerClient.cpp
  scripts/windows_build.sh
  testutils/custom-params/CMakeLists.txt
  testutils/custom-params/include/testutils/CustomParameters.hpp
  testutils/custom-params/src/CustomParameters.cpp
Labels: bug

#13 Added option to enable multi threaded compilation on Windows
  CMakeLists.txt
  README.md
Labels: enhancement

#15 Travis CI setup without docker
  .travis.yml
  scripts/linux_build.sh
Labels: CI

#17 Fixed generation of tester apps when configuring SDK on iOS
  .gitignore
  cmake/ios/gen_ios_test.cmake
  cmake/ios/ios_test.sh.in
Labels: bug

#14 Added iOS template for the example applications
  docs/dataservice-write-example.md
  examples/dataservice-write/CMakeLists.txt
  examples/dataservice-write/ios/AppDelegate.mm
  examples/dataservice-write/ios/Info.plist
  examples/dataservice-write/ios/ViewController.mm
  examples/dataservice-write/ios/resources/dummy.txt
  examples/helpers/ios/AppDelegate.h
  examples/helpers/ios/AppDelegate.mm
  examples/helpers/ios/CMakeLists.txt.in
  examples/helpers/ios/Info.plist.in
  examples/helpers/ios/ViewController.h
  examples/helpers/ios/ViewController.mm
  examples/helpers/ios/main.mm
  examples/helpers/ios/resources/Main.storyboard
Labels: documentation, enhancement

#19 This will setup Travis CI to use clang and gcc compilers.
  .travis.yml
Labels: CI

#21 Add PR build verification for OSX
  .travis.yml
  scripts/linux/build.sh
  scripts/linux/test.sh
  scripts/windows/build.sh
Labels: CI

#16 Allow method chaining in logger classes
  olp-cpp-sdk-core/include/olp/core/logging/Appender.h
  olp-cpp-sdk-core/include/olp/core/logging/Configuration.h
  olp-cpp-sdk-core/include/olp/core/logging/ConsoleAppender.h
  olp-cpp-sdk-core/include/olp/core/logging/DebugAppender.h
  olp-cpp-sdk-core/include/olp/core/logging/FileAppender.h
  olp-cpp-sdk-core/include/olp/core/logging/FilterGroup.h
  olp-cpp-sdk-core/include/olp/core/logging/MessageFormatter.h
  olp-cpp-sdk-core/src/logging/Configuration.cpp
  olp-cpp-sdk-core/src/logging/ConsoleAppender.cpp
  olp-cpp-sdk-core/src/logging/DebugAppender.cpp
  olp-cpp-sdk-core/src/logging/FileAppender.cpp
Labels: enhancement

#24 Remove boost::functional and boost::typeIndex dependency
  olp-cpp-sdk-core/include/olp/core/geo/projection/EquirectangularProjection.h
  olp-cpp-sdk-core/include/olp/core/geo/projection/IProjection.h
  olp-cpp-sdk-core/include/olp/core/geo/projection/IdentityProjection.h
  olp-cpp-sdk-core/include/olp/core/geo/projection/SphereProjection.h
  olp-cpp-sdk-core/include/olp/core/geo/projection/WebMercatorProjection.h
  olp-cpp-sdk-core/include/olp/core/geo/tiling/ITilingScheme.h
  olp-cpp-sdk-core/include/olp/core/geo/tiling/TilingScheme.h
  olp-cpp-sdk-core/include/olp/core/math/AlignedBox.h
  olp-cpp-sdk-core/include/olp/core/utils/TypeId.h
  olp-cpp-sdk-core/src/geo/projection/EquirectangularProjection.cpp
  olp-cpp-sdk-core/src/geo/projection/IdentityProjection.cpp
  olp-cpp-sdk-core/src/geo/projection/SphereProjection.cpp
  olp-cpp-sdk-core/src/geo/projection/WebMercatorProjection.cpp
Labels: enhancement

#25 Add build verification for Windows on Azure
  azure-pipelines.yml
  scripts/windows/build.sh
Labels: CI

#38 Build EdgeNetworkProtocol.jar with olp-cpp-sdk-core for Android
  olp-cpp-sdk-core/CMakeLists.txt
Labels: bug

#45 DataRequest key generation optimization
  olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/DataRequest.h
  olp-cpp-sdk-dataservice-read/src/repositories/DataRepository.cpp
Labels: enhancement

#46 Configure Travis CI for Android & IOS build
  .travis.yml
  scripts/android/build.sh
  scripts/ios/build.sh
Labels: CI

#47 PrefetchTilesProvider logging enhancement
  olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PrefetchTilesRequest.h
  olp-cpp-sdk-dataservice-read/src/MultiRequestContext.h
  olp-cpp-sdk-dataservice-read/src/PrefetchTilesProvider.cpp
Labels: enhancement

#42 Adds TaskScheduler base class for sync/async task scheduling.
  olp-cpp-sdk-core/include/olp/core/thread/TaskScheduler.h
Labels: enhancement

#43 CatalogClientImpl logging improvement
  olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogRequest.h
  olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/CatalogVersionRequest.h
  olp-cpp-sdk-dataservice-read/include/olp/dataservice/read/PartitionsRequest.h
  olp-cpp-sdk-dataservice-read/src/CatalogClientImpl.cpp
  olp-cpp-sdk-dataservice-read/src/MultiRequestContext.h
  olp-cpp-sdk-dataservice-read/src/repositories/CatalogRepository.cpp
  olp-cpp-sdk-dataservice-read/src/repositories/PartitionsRepository.cpp
Labels: enhancement

#49 Remove specialized methods from logging::Configuration class.
  olp-cpp-sdk-core/include/olp/core/logging/Configuration.h
  olp-cpp-sdk-core/src/logging/Configuration.cpp
Labels: enhancement

#41 Add new network inteface
  olp-cpp-sdk-core/CMakeLists.txt
  olp-cpp-sdk-core/include/olp/core/network2/Network.h
  olp-cpp-sdk-core/include/olp/core/network2/NetworkProxySettings.h
  olp-cpp-sdk-core/include/olp/core/network2/NetworkRequest.h
  olp-cpp-sdk-core/include/olp/core/network2/NetworkResponse.h
  olp-cpp-sdk-core/include/olp/core/network2/NetworkSettings.h
  olp-cpp-sdk-core/include/olp/core/network2/NetworkTypes.h
  olp-cpp-sdk-core/src/network2/Network.cpp
  olp-cpp-sdk-core/src/network2/NetworkProxySettings.cpp
  olp-cpp-sdk-core/src/network2/NetworkRequest.cpp
  olp-cpp-sdk-core/src/network2/NetworkResponse.cpp
  olp-cpp-sdk-core/src/network2/NetworkSettings.cpp
Labels: enhancement

#48 Adds generic thread safe queue for both FIFO and LIFO usage.
  olp-cpp-sdk-core/CMakeLists.txt
  olp-cpp-sdk-core/include/olp/core/thread/SyncQueue.h
  olp-cpp-sdk-core/include/olp/core/thread/SyncQueue.inl
  olp-cpp-sdk-core/tests/thread/CMakeLists.txt
  olp-cpp-sdk-core/tests/thread/unittest/SyncQueueTest.cpp
  scripts/linux/test.sh
Labels: enhancement

#44 Added support of CMAKE_JAVA_TARGET_OUTPUT_DIR in examples
  examples/helpers/android/app/CMakeLists.txt.in
  examples/helpers/cmake/gen_android_example.cmake.in
Labels: enhancement

#54 Configure Travis CI for code coverage
  .travis.yml
  README.md
  scripts/linux/build.sh
  scripts/linux/test.sh
Labels: CI

#55 Fix badges in README.md file.
  README.md
Labels: CI

#52 Add ThreadPoolTaskScheduler implementing TaskScheduler class.
  olp-cpp-sdk-core/CMakeLists.txt
  olp-cpp-sdk-core/cmake/CompileChecks.cmake
  olp-cpp-sdk-core/include/olp/core/thread/ThreadPoolTaskScheduler.h
  olp-cpp-sdk-core/include/olp/core/utils/WarningWorkarounds.h
  olp-cpp-sdk-core/src/thread/ThreadPoolTaskScheduler.cpp
  olp-cpp-sdk-core/tests/thread/unittest/ThreadPoolTaskSchedulerTest.cpp
Labels: enhancement
