Repository heremaps/here-data-sdk-cpp, pull requests merged in 2019-09, with the labels that each got.

#109 Fixes the cache clear key for partitions and the according test.
  olp-cpp-sdk-dataservice-read/src/repositories/PartitionsCacheRepository.cpp
  olp-cpp-sdk-dataservice-read/test/unit/src/CatalogClientTest.cpp
  scripts/linux/fv/gitlab-olp-dataservice-read-test.sh
  scripts/linux/psv/travis_test_psv.sh
Labels: bug

#110 Make SDIIConcurrentPublishSameIngestApi test more stable.
  olp-cpp-sdk-dataservice-write/test/unit/TestStreamLayerClient.cpp
Labels: bug

#116 Fixed problem with inability to send new requests with NetworkAndroid
  olp-cpp-sdk-core/src/http/android/NetworkAndroid.cpp
  olp-cpp-sdk-core/src/http/android/NetworkAndroid.h
Labels: bug

#117 Add a link to API reference
  docs/GettingStartedGuide.md
Labels: documentation

#131 Removed WinHttp inheritance from std::enable_shared_from_this
  olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.cpp
  olp-cpp-sdk-core/src/http/winhttp/NetworkWinHttp.h
Labels: bug

#130 OLPEDGE-383. Shared libs ON. Libsegfault lib added.
  .gitlab-ci.yml
  .travis.yml
  scripts/linux/fv/gitlab_build_fv.sh
  scripts/linux/psv/travis_build_psv.sh
Labels: CI

#132 Keep network instance in unit tests alive until inner thread is running
  olp-cpp-sdk-core/src/http/curl/NetworkCurl.cpp
  olp-cpp-sdk-dataservice-write/test/unit/TestIndexLayerClient.cpp
  olp-cpp-sdk-dataservice-write/test/unit/TestStreamLayerClient.cpp
  olp-cpp-sdk-dataservice-write/test/unit/TestVersionedLayerClient.cpp
  olp-cpp-sdk-dataservice-write/test/unit/TestVolatileLayerClient.cpp
Labels: bug

#121 Adapts StreamLayerClient to use TaskScheduler for Flush context.
  examples/dataservice-write/example.cpp
  olp-cpp-sdk-dataservice-write/src/StreamLayerClientImpl.cpp
  olp-cpp-sdk-dataservice-write/test/unit/TestStreamLayerClient.cpp
Labels: enhancement

#163 Fixed mistake when executable mode is not set for .sh
  scripts/linux/fv/gitlab-olp-cpp-sdk-core-test.sh
Labels: CI

#172 Adapt Azure badge and link to point to new repository name.
  README.md
Labels: documentation

#183 Fixed minor bug, so translate_report and deploy will run on schedule only. [skip travis]
  .gitlab-ci.yml
Labels: CI

#182 Adds the KeyValueCache as shared to the OlpClientSettings.
  olp-cpp-sdk-core/include/olp/core/client/OlpClientSettings.h
  olp-cpp-sdk-core/include/olp/core/client/OlpClientSettingsFactory.h
  olp-cpp-sdk-core/src/client/OlpClientSettingsFactory.cpp
Labels: enhancement
